# Use the official MySQL image
FROM mysql:latest

# Set environment variables for database setup
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=meow
ENV MYSQL_DB=mysql
ENV MYSQL_ROOT_PASSWORD=meow

# Expose the port MySQL runs on
EXPOSE 3306
