# Use the official Python image
FROM python:latest




# Create a new user and set permissions
RUN useradd -m rachel


# Set ownership of the working directory
WORKDIR /app
RUN chown -R rachel /app




# Create a virtual environment
RUN python -m venv /venv

# Activate the virtual environment
ENV PATH="/venv/bin:${PATH}"

RUN pip install pandas sqlalchemy psycopg2-binary jupyter pyarrow
RUN pip install mysql-connector-python pandas scipy scikit-learn matplotlib


#switch to non-root user
USER rachel


# Copy ETL scripts or Jupyter notebooks into the container
COPY ./data/* /app/rawdata/
COPY hw1.ipynb /app/hw1.ipynb  # Optional: If you have notebooks to copy

# Expose the Jupyter Notebook port
EXPOSE 8888

# Command to run Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
CMD ["/bin/bash"]
